require_relative "fact_bank"

ASSISTED_DYING_SOURCES = {
  bill: [ "UK Parliament: Terminally Ill Adults (End of Life) Bill", "https://bills.parliament.uk/publications/61635/documents/6735" ],
  notes: [ "House of Commons Library: Terminally Ill Adults bills", "https://commonslibrary.parliament.uk/terminally-ill-adults-end-of-life-bills/" ],
  impact: [ "UK Government: assisted-dying impact assessment", "https://www.gov.uk/government/publications/terminally-ill-adults-end-of-life-bill-impact-assessment" ],
  equality: [ "UK Government: assisted-dying equality impact assessment", "https://www.gov.uk/government/publications/terminally-ill-adults-end-of-life-bill-equality-impact-assessment/terminally-ill-adults-end-of-life-bill-equality-impact-assessment-html-version-as-introduced-to-the-lords" ],
  nhs: [ "NHS England: inequalities in palliative and end-of-life care", "https://www.england.nhs.uk/eolc/addressing-inequalities-in-palliative-and-end-of-life-care/" ],
  ons: [ "Office for National Statistics: suicide following severe health diagnoses", "https://www.ons.gov.uk/peoplepopulationandcommunity/birthsdeathsandmarriages/deaths/bulletins/suicidesamongpeoplediagnosedwithseverehealthconditionsengland/2017to2020" ],
  cps: [ "Crown Prosecution Service: suicide and assisted suicide", "https://www.cps.gov.uk/legal-guidance/suicide-policy-prosecutors-respect-cases-encouraging-or-assisting-suicide" ]
}.freeze

ASSISTED_DYING_FACTS = FactBank.build([
  [ "Under the proposed eligibility rule, what minimum age would an applicant need to have reached?",
    [ "18", "16 with parental agreement", "21", "There would be no minimum" ], 0,
    "The proposed scheme was limited to adults aged 18 or over.", :bill, 0, 1, "The age boundary defines scope but is not a principal argument for or against the policy." ],
  [ "Where would the proposed law apply?",
    [ "Throughout Europe", "England and Wales", "Scotland only", "Northern Ireland only" ], 1,
    "The proposal applied to England and Wales; health and criminal law arrangements differ elsewhere in the UK.", :bill, 0, 1, "Territorial scope prevents mistaken comparisons but carries little independent normative weight." ],
  [ "Which prognosis was required by the proposed definition of terminal illness?",
    [ "Any incurable diagnosis", "A condition expected to shorten life someday", "Death reasonably expected within six months", "A disability requiring daily assistance" ], 2,
    "Eligibility required an inevitably progressive illness or disease from which death could reasonably be expected within six months.", :bill, 1, 3, "The six-month terminal criterion is foundational to the proposition's narrow scope." ],
  [ "Could disability or mental disorder alone satisfy the proposed terminal-illness requirement?",
    [ "Yes, whenever care is expensive", "Yes, after one consultation", "Only for people over 75", "No" ], 3,
    "Disability and mental disorder did not by themselves make a person terminally ill under the proposal.", :bill, 1, 3, "Excluding disability or mental illness alone is foundational to evaluating equality and expansion concerns." ],
  [ "What decision-making ability would an applicant need?",
    [ "Capacity to make the decision to end their life", "Ability to name every medication", "Agreement from all relatives", "A previous advance directive alone" ], 0,
    "The person would need capacity for this decision at the relevant stages; capacity is decision-specific.", :bill, 1, 3, "Valid autonomous choice depends fundamentally on decision-making capacity." ],
  [ "What would both assessing doctors have to find about the applicant's wish?",
    [ "That it followed a family vote", "That it was clear, settled, informed and voluntary", "That it began before diagnosis", "That no one had discussed palliative care" ], 1,
    "Both doctors would assess whether the wish was clear, settled and informed and made voluntarily without coercion or pressure.", :bill, 1, 3, "Voluntariness and protection from coercion are foundational safeguards." ],
  [ "How many independent medical assessments did the proposal require before panel review?",
    [ "None", "One", "Two", "Five" ], 2,
    "A coordinating doctor and a separate independent doctor would each assess eligibility.", :bill, 1, 2, "Independent repetition is a significant safeguard but cannot by itself guarantee detection of every error." ],
  [ "What followed the first doctor's positive assessment before the second assessment?",
    [ "Immediate provision of medication", "A compulsory public hearing", "Automatic approval by relatives", "A reflection period" ], 3,
    "The bill provided a seven-day first reflection period before the independent doctor's assessment, subject to limited exceptions where death was imminent.", :bill, 1, 2, "Time for reconsideration materially affects whether a request is enduring." ],
  [ "Who would make the additional independent decision after the two doctors?",
    [ "A multidisciplinary Assisted Dying Review Panel", "The applicant's employer", "A local referendum", "The pharmaceutical manufacturer" ], 0,
    "The proposal replaced the earlier High Court stage with a multidisciplinary panel including legal, psychiatric and social-work expertise.", :notes, 1, 3, "Independent review beyond clinicians is foundational to the proposed safeguard structure." ],
  [ "Who would perform the final act causing death under the proposed model?",
    [ "A relative chosen by the applicant", "The applicant themselves", "A panel member", "Any available clinician" ], 1,
    "A clinician could prepare the approved substance, but the eligible person would have to self-administer it.", :bill, 1, 3, "Self-administration materially distinguishes this proposal from voluntary euthanasia." ],
  [ "Would an eligible person be obliged to proceed after approval?",
    [ "Yes, within 24 hours", "Yes, unless a doctor objected", "No; consent could be withdrawn", "Only the panel could cancel it" ], 2,
    "Approval created an option, not a duty. The person could revoke declarations or decide not to take the substance.", :bill, 1, 2, "Continuing choice is a significant component of autonomy." ],
  [ "What is the present legal position on assisting another person's suicide in England and Wales?",
    [ "It is a licensed medical service", "It is always treated as murder", "It is lawful if no money changes hands", "It is a criminal offence, subject to prosecutorial judgment" ], 3,
    "Encouraging or assisting suicide is an offence; prosecutors apply a published public-interest policy to individual cases.", :cps, 1, 2, "The present law establishes what reform would change and why families may face uncertainty." ],
  [ "Does excellent palliative care always remove every person's pain, breathlessness or loss of control?",
    [ "No", "Yes, in every diagnosis", "Only outside hospitals", "Only if morphine is prohibited" ], 0,
    "Palliative care relieves suffering for many people but cannot guarantee that every symptom or concern will be acceptable to every patient.", :impact, 1, 2, "Whether suffering can remain refractory is significant to the autonomy case." ],
  [ "Is access to specialist palliative and end-of-life care uniform across diagnoses and communities?",
    [ "Yes, by statutory formula", "No; NHS England identifies persistent inequalities", "Only age affects access", "No information is collected" ], 1,
    "NHS England identifies poorer access and experience among some diagnoses, deprived and rural populations and marginalised groups.", :nhs, -1, 3, "Unequal alternatives are foundational to concern that choice could be shaped by inadequate care." ],
  [ "How precise is an individual clinician's six-month prognosis?",
    [ "Exact to the day", "Always within one week", "Uncertain, especially for non-cancer illnesses", "Impossible to estimate in any case" ], 2,
    "Population patterns inform prognosis, but individual survival estimates remain uncertain and vary by disease trajectory.", :impact, -1, 3, "Eligibility depends on prognosis, making unavoidable uncertainty foundational." ],
  [ "Can a person have capacity while making a decision others consider unwise?",
    [ "Never", "Only with family permission", "Only if independently wealthy", "Yes" ], 3,
    "Mental-capacity law does not equate an unwise decision with incapacity; the question is whether the person can understand, retain, use and weigh information and communicate a choice.", :bill, 0, 2, "This distinction is significant to avoiding both paternalism and inadequate assessment." ],
  [ "What does evidence about suicide after diagnosis of severe illness show?",
    [ "Risk can be elevated after some diagnoses", "No diagnosed person dies by suicide", "Risk is identical for every condition", "Only relatives are affected" ], 0,
    "ONS analysis found elevated suicide rates following diagnosis or treatment for several severe conditions, especially in some early periods.", :ons, 1, 2, "Existing unassisted deaths are significant to the claim that prohibition does not eliminate desperate action." ],
  [ "Would the proposal allow a binding advance request to cause death after the person had lost capacity?",
    [ "Yes, for any dementia diagnosis", "No", "Only after ten years", "Only if relatives administered it" ], 1,
    "The person had to retain capacity and personally self-administer; an earlier request could not substitute after capacity was lost.", :bill, 1, 2, "Excluding advance requests materially limits scope and answers a common misconception." ],
  [ "Which diagnosis accounted for most assisted-dying applicants in comparable jurisdictions used by the impact assessment?",
    [ "Broken bones", "Dementia alone", "Cancer", "Short-sightedness" ], 2,
    "Government analysis reported cancer as the majority diagnosis among applicants in comparable terminal-illness jurisdictions.", :equality, 0, 1, "Diagnostic composition is useful context but does not decide the principle." ],
  [ "What did the government estimate about how many approved applicants would complete an assisted death?",
    [ "Every applicant", "Fewer than one in twenty", "No estimate was attempted", "Around three in five" ], 3,
    "The equality assessment estimated that roughly three in five applicants would complete the process, based on overseas data.", :equality, 0, 1, "Non-use shows approval and eventual action differ, but the estimate is not central." ],
  [ "Why do official projections of assisted-death numbers have wide ranges?",
    [ "Uptake and overseas comparability are uncertain", "The adult population is unknown", "Deaths are never registered", "The law fixes no eligibility rules" ], 0,
    "Uptake trends, implementation and differences between foreign systems make projections uncertain.", :impact, 0, 1, "Forecast uncertainty matters for service planning but is supporting rather than decisive evidence." ],
  [ "Would doctors be compelled to participate personally in providing assisted deaths?",
    [ "Yes, regardless of belief", "No; conscientious non-participation was protected", "Only retired doctors could refuse", "Only a panel could object" ], 1,
    "The proposal protected clinicians from being required to participate, while information and service-access arrangements remained necessary.", :bill, 1, 2, "Conscience protection is significant to workforce and ethical concerns." ],
  [ "Could family financial interest be relevant when assessing coercion or pressure?",
    [ "No, finances are legally invisible", "Only if a will names a charity", "Yes", "Only after death" ], 2,
    "Assessors and the panel would need to consider coercion and pressure, which can be subtle and may include dependency, abuse or financial interest.", :bill, -1, 2, "The difficulty of detecting concealed pressure is a significant safeguarding concern." ],
  [ "Can any safeguard reduce coercion, diagnostic error and prognostic error to literally zero?",
    [ "Yes, if forms are signed", "Yes, after two appointments", "Only in private care", "No" ], 3,
    "Layered safeguards can reduce risk but no medical or legal decision system can eliminate deception, error or undue influence completely.", :impact, -1, 3, "Residual irreversible error is foundational to opposition even where safeguards are substantial." ],
  [ "Would legalisation make good palliative care unnecessary?",
    [ "No", "Yes, hospices could close", "Only cancer care would remain", "Pain relief would become unlawful" ], 0,
    "The policy and equality assessments treat assisted dying as an additional choice, not a substitute for palliative and end-of-life care.", :equality, 0, 2, "The relationship between services is significant because poor provision could distort choice." ],
  [ "Why might clinicians disagree honestly about whether someone has six months to live?",
    [ "Medical records contain no diagnoses", "Disease trajectories vary between individuals", "Doctors use different calendars", "The period has no stated length" ], 1,
    "Even with the same information, uncertain disease trajectories can support different reasonable prognoses.", :impact, -1, 2, "Inter-observer uncertainty is significant because it affects access and consistency." ],
  [ "What information would an applicant need before making an informed decision?",
    [ "Only the substance's colour", "Only the panel members' names", "Diagnosis, prognosis, treatment and palliative options", "The voting record of their MP" ], 2,
    "The doctors would need to ensure the person understood diagnosis, prognosis, available treatment and palliative or hospice care.", :bill, 1, 2, "Informed choice depends significantly on realistic knowledge of alternatives." ],
  [ "Could Parliament later broaden eligibility without passing further legislation?",
    [ "Yes, any doctor could rewrite the Act", "Yes, a patient could waive the statute", "Only an overseas court could do so", "Not beyond powers expressly delegated by the Act" ], 3,
    "Core statutory eligibility could not simply be ignored; substantial expansion would ordinarily require Parliament to legislate, though delegated powers and judicial interpretation still matter.", :bill, 0, 2, "This clarifies, without dismissing, concerns about later democratic expansion." ],
  [ "Does experience in one overseas jurisdiction prove that England and Wales would produce identical outcomes?",
    [ "No", "Yes, populations are interchangeable", "Only cost outcomes transfer", "Only safeguards transfer" ], 0,
    "Overseas evidence is relevant but differences in law, health systems, reporting and culture limit direct prediction.", :impact, 0, 1, "Transferability is a supporting methodological qualification." ],
  [ "What is the central unresolved judgement after the eligibility rules and evidence are understood?",
    [ "Whether terminal illness exists", "How autonomy should be weighed against safeguarding risks", "Whether doctors can prescribe any medicine", "Whether death can be postponed indefinitely" ], 1,
    "The evidence identifies likely benefits, limits and risks. It cannot uniquely determine how society should weigh a competent person's autonomy against safeguarding vulnerable people from irreversible harm.", :equality, 0, 1, "The synthesis makes the boundary between factual knowledge and moral weighting explicit." ]
], ASSISTED_DYING_SOURCES)

# Keep answer length from becoming a useful substitute for knowledge.
ASSISTED_DYING_FACTS.fetch(4)[:options][2] = "Agreement from every close relative and the treating consultant"
ASSISTED_DYING_FACTS.fetch(5)[:options][0] = "That it followed a recorded and unanimous family vote"
