require_relative "fact_bank"

DEATH_PENALTY_SOURCES = {
  bjs: [ "Bureau of Justice Statistics: Capital Punishment", "https://bjs.ojp.gov/topics/corrections/capital-punishment" ],
  doj: [ "US Department of Justice: Federal Death Penalty", "https://www.justice.gov/d9/2024-12/Review%20of%20the%20Federal%20Execution%20Protocol.pdf" ],
  scotus: [ "US Supreme Court: Furman v. Georgia", "https://supreme.justia.com/cases/federal/us/408/238/" ],
  gregg: [ "US Supreme Court: Gregg v. Georgia", "https://supreme.justia.com/cases/federal/us/428/153/" ],
  kennedy: [ "US Supreme Court: Kennedy v. Louisiana", "https://supreme.justia.com/cases/federal/us/554/407/" ],
  roper: [ "US Supreme Court: Roper v. Simmons", "https://supreme.justia.com/cases/federal/us/543/551/" ],
  atkins: [ "US Supreme Court: Atkins v. Virginia", "https://supreme.justia.com/cases/federal/us/536/304/" ],
  nas: [ "National Academies: Deterrence and the Death Penalty", "https://nap.nationalacademies.org/catalog/13363/deterrence-and-the-death-penalty" ],
  nij: [ "National Institute of Justice: Five Things About Deterrence", "https://nij.ojp.gov/topics/articles/five-things-about-deterrence" ],
  nist: [ "National Institute of Standards and Technology: Forensic Science", "https://www.nist.gov/forensic-science" ],
  gao: [ "US Government Accountability Office: Death Penalty Sentencing", "https://www.gao.gov/products/ggd-90-57" ],
  exoneration: [ "National Registry of Exonerations", "https://www.law.umich.edu/special/exoneration/Pages/about.aspx" ],
  gallup: [ "Gallup: Death Penalty Support Trends", "https://news.gallup.com/poll/178823/death-penalty-support-trends.aspx" ],
  un: [ "United Nations: Death penalty", "https://www.ohchr.org/en/topic/death-penalty" ]
}.freeze

DEATH_PENALTY_FACTS = FactBank.build([
  [ "Which governments can currently prescribe capital punishment in the United States?",
    [ "The federal government and states whose law retains it", "Only cities", "Only the United Nations", "Every county regardless of state law" ], 0,
    "Capital punishment exists under federal law and in some states; other states have abolished it or do not carry out executions.", :bjs, 0, 3,
    "The proposition's federal-and-state scope is foundational to understanding what abolition would change." ],
  [ "What did Furman v. Georgia do in 1972?",
    [ "Required executions for murder", "Invalidated then-existing death-penalty schemes, producing a nationwide halt", "Abolished life imprisonment", "Approved lethal injection" ], 1,
    "The fragmented decision found the challenged arbitrary schemes unconstitutional under the Eighth and Fourteenth Amendments.", :scotus, 1, 3,
    "The constitutional history explains why modern statutes use guided procedures." ],
  [ "What did Gregg v. Georgia hold in 1976?",
    [ "Capital punishment is mandatory", "Only federal executions are lawful", "The death penalty is not invariably unconstitutional under guided statutes", "Juries may not consider mitigation" ], 2,
    "Gregg upheld Georgia's revised framework, allowing capital punishment to resume under procedural safeguards.", :gregg, -1, 3,
    "Current legality and the rationale for guided discretion are foundational." ],
  [ "For which crime did Kennedy v. Louisiana bar the death penalty where the victim did not die?",
    [ "Tax fraud", "Treason", "Espionage", "Child rape" ], 3,
    "The Court held capital punishment disproportionate for child rape when the crime neither resulted nor was intended to result in death.", :kennedy, 0, 2,
    "Constitutional limits clarify that the death penalty is not available for every grave offence." ],
  [ "May a person be executed for a crime committed while under 18?",
    [ "No", "Yes in every state", "Only with parental consent", "Only federally" ], 0,
    "Roper v. Simmons held juvenile executions unconstitutional.", :roper, 1, 2,
    "Age restrictions materially define the eligible population." ],
  [ "May a state execute a person with intellectual disability?",
    [ "Yes without assessment", "No, under Atkins v. Virginia", "Only by jury vote", "Only for federal crimes" ], 1,
    "Atkins held such executions violate the Eighth Amendment, leaving states procedures to determine eligibility.", :atkins, 1, 2,
    "Culpability limits are significant to proportional-punishment arguments." ],
  [ "What is an aggravating factor in a capital case?",
    [ "Evidence requiring acquittal", "A prison rule", "A statutorily specified circumstance supporting death eligibility", "Any fact reported by media" ], 2,
    "Modern capital statutes narrow eligibility through specified aggravators, while mitigation argues against death.", :gregg, -1, 2,
    "Eligibility rules determine how narrowly capital punishment is applied." ],
  [ "What is mitigating evidence?",
    [ "Evidence increasing the offence count", "Proof of a different victim", "A mandatory death sentence", "Information about circumstances or character supporting a sentence below death" ], 3,
    "Capital sentencers must be able to consider relevant mitigation.", :gregg, -1, 2,
    "Individualised sentencing is a central safeguard but also a source of discretion." ],
  [ "What did the National Academies conclude about existing studies claiming the death penalty deters homicide?",
    [ "They were not informative about the causal effect", "They proved a precise number saved", "They proved executions increase every murder rate", "No studies existed" ], 0,
    "The review found the research unable to distinguish capital punishment's effect from alternatives and advised against using it to guide policy.", :nas, -1, 3,
    "Deterrence is a central justification, and the evidential uncertainty is foundational." ],
  [ "According to deterrence research, which generally matters more: certainty of being caught or severity of punishment?",
    [ "Severity alone", "Certainty", "Neither can matter", "Publicity alone" ], 1,
    "NIJ summarises evidence that certainty of apprehension has a stronger deterrent effect than increasing punishment severity.", :nij, -1, 3,
    "This directly bears on whether execution adds deterrence beyond imprisonment." ],
  [ "Can comparison of murder rates in death-penalty and non-death-penalty states by itself establish causation?",
    [ "Yes, always", "Yes if one year is used", "No; states differ in many other relevant ways", "No statistics may ever inform policy" ], 2,
    "Confounding factors include policing, demographics, inequality, gun prevalence and regional history.", :nas, 0, 3,
    "Causal inference is foundational to interpreting deterrence claims responsibly." ],
  [ "What punishment is the principal severe alternative to execution in abolition debates?",
    [ "A small fine", "Community service", "Automatic release", "Life imprisonment without parole" ], 3,
    "The relevant policy comparison is usually death versus permanent imprisonment, not death versus no punishment.", :nas, -1, 3,
    "The realistic alternative is foundational to judging deterrence, safety, cost and retribution." ],
  [ "What makes an execution different from imprisonment after a wrongful conviction is discovered?",
    [ "It is irreversible", "It guarantees new evidence", "It can be refunded", "It automatically identifies the true offender" ], 0,
    "A living prisoner can be released and compensated; an executed person cannot be restored.", :exoneration, 1, 3,
    "Irreversibility is the central consequence of inevitable justice-system error." ],
  [ "Have people sentenced to death later been exonerated?",
    [ "No", "Yes", "Only outside the US", "Only before 1900" ], 1,
    "Documented exonerations include people removed from death row after evidence of innocence or serious case failure.", :exoneration, 1, 3,
    "Observed wrongful capital convictions are foundational to assessing irreversible-error risk." ],
  [ "Which evidence has contributed to some wrongful-conviction reversals?",
    [ "Astrology", "Opinion polling", "DNA testing", "Election results" ], 2,
    "Post-conviction DNA testing can exclude a convicted person or identify another contributor, though biological evidence is unavailable in many cases.", :nist, 1, 2,
    "The capacity to uncover error is significant, while its absence does not prove accuracy." ],
  [ "Are forensic techniques all supported by equally strong validation evidence?",
    [ "Yes", "Yes if used in court", "Only prosecution techniques are", "No; reliability and error-rate evidence vary by discipline" ], 3,
    "NIST works to develop standards and strengthen scientific foundations because forensic methods vary in validation and limitations.", :nist, 1, 3,
    "Evidence reliability is foundational where error can produce an irreversible sentence." ],
  [ "What did GAO's review find about race-of-victim effects in death-penalty studies?",
    [ "A pattern of higher death-sentencing likelihood when victims were white appeared in most reviewed studies", "No study examined race", "Only defendant wealth mattered", "Race effects were legally required" ], 0,
    "GAO found a remarkably consistent race-of-victim influence across studies, while defendant-race findings were less consistent.", :gao, 1, 3,
    "Systematic disparities directly bear on fairness and equal application." ],
  [ "Does a statistical racial disparity prove intentional bias by every juror or prosecutor?",
    [ "Yes", "No; it identifies unequal patterns but not every individual's motive", "Only in federal cases", "Statistics can never reveal disparities" ], 1,
    "Disparity may arise through multiple stages and mechanisms; intent and causal pathway require separate evidence.", :gao, 0, 2,
    "This guards against overstating what aggregate evidence establishes." ],
  [ "Why can geography affect capital sentencing?",
    [ "Federal law changes hourly", "Juries cannot travel", "States and local prosecutors differ in law, policy, resources and charging practice", "Every county has identical practice" ], 2,
    "Similar crimes may face different capital exposure depending on jurisdiction.", :bjs, 1, 3,
    "Geographic arbitrariness is central to equal-treatment concerns." ],
  [ "Who usually decides whether to seek death in an eligible prosecution?",
    [ "The victim alone", "The media", "A random citizen", "The responsible prosecuting authority, subject to governing law and policy" ], 3,
    "Prosecutorial charging decisions determine which eligible cases proceed capitally.", :doj, 0, 2,
    "Discretion is significant to consistency, local control and arbitrariness." ],
  [ "Why are capital trials generally more expensive than comparable non-capital murder trials?",
    [ "They require specialised, longer guilt and penalty proceedings plus extensive review", "Execution drugs are the only cost", "Jurors receive the sentence money", "Prisons charge by verdict word" ], 0,
    "Death eligibility, expert work, jury selection, mitigation investigation and mandatory review add resources.", :doj, -1, 3,
    "Opportunity cost and public expense are central practical consequences." ],
  [ "Would abolition eliminate the cost of imprisoning people convicted of aggravated murder?",
    [ "Yes", "No; long-term secure imprisonment would remain", "Only state prisons would close", "All convictions would be erased" ], 1,
    "A fair cost comparison includes the continuing cost of life imprisonment as well as capital litigation and confinement.", :bjs, 0, 3,
    "The correct counterfactual is foundational to avoiding misleading cost claims." ],
  [ "What is clemency?",
    [ "A jury conviction", "A new crime", "Executive power to commute or pardon a sentence", "Automatic release after appeal" ], 2,
    "Governors or the President may provide a final mercy or error-correction mechanism within their jurisdiction.", :doj, -1, 2,
    "Clemency is a significant safeguard but is discretionary and political." ],
  [ "Does lengthy appellate review eliminate all risk of executing an innocent person?",
    [ "Yes", "Yes after ten years", "Only with a confession", "No; it reduces risk but cannot guarantee error-free outcomes" ], 3,
    "Review can find legal and factual errors, yet evidence may be lost, counsel may fail and some innocence claims remain unresolved.", :exoneration, 1, 3,
    "Residual error after safeguards is foundational because execution is irreversible." ],
  [ "What retributive principle is commonly offered in support of capital punishment?",
    [ "Some murders deserve the most severe proportionate punishment", "Punishment should maximise profit", "Every crime deserves death", "Trials are unnecessary" ], 0,
    "Retribution concerns deserved punishment rather than empirical deterrence.", :gregg, -1, 3,
    "Retribution is a central moral justification and cannot be settled by deterrence statistics alone." ],
  [ "What moral principle commonly supports abolition?",
    [ "Murder should be unpunished", "The state should not deliberately take a prisoner's life", "Courts should ignore victims", "All imprisonment is identical" ], 1,
    "Abolitionists argue human dignity, fallibility or limits on state power rule out execution even for grave crimes.", :un, 1, 3,
    "The intrinsic moral objection is central and distinct from instrumental evidence." ],
  [ "Do all murder victims' relatives hold the same view of execution?",
    [ "Yes, all favour it", "Yes, all oppose it", "No; views differ", "Relatives are legally barred from views" ], 2,
    "Some seek execution as justice; others oppose it or describe prolonged capital proceedings as harmful.", :doj, 0, 2,
    "Variation cautions against invoking victims' families as one uniform interest." ],
  [ "How did US public support for the death penalty in 2025 compare with its 1994 peak?",
    [ "It was higher", "It was identical at 80%", "No polling exists", "It was much lower—about 52% versus 80%" ], 3,
    "Gallup recorded 52% favouring in 2025, down from 80% in 1994.", :gallup, 1, 1,
    "Public opinion is useful democratic context but does not determine factual effectiveness or justice." ],
  [ "Is capital punishment the global norm?",
    [ "No; most countries have abolished it in law or practice", "Yes; every UN member executes", "Only Europe retains it", "International practice is unknown" ], 0,
    "A majority of states worldwide no longer execute, though populous retentionist countries remain.", :un, 1, 2,
    "Comparative practice informs claims about necessity and human-rights standards." ],
  [ "What is the most defensible synthesis of the evidence?",
    [ "Execution is proven to deter every murder", "Capital punishment expresses severe retribution, but deterrence is unproven and irreversibility, error, disparity and cost are material concerns", "Capital cases contain no safeguards", "Abolition means releasing murderers" ], 1,
    "An informed judgement distinguishes the moral case for retribution from uncertain deterrence evidence and weighs safeguards against documented error and unequal application.", :nas, 0, 3,
    "A balanced synthesis of the central justification, evidence and risks is foundational." ]
], DEATH_PENALTY_SOURCES)
