require_relative "fact_bank"

ECHR_SOURCES = {
  commons: [ "House of Commons Library: ECHR and Human Rights Act", "https://commonslibrary.parliament.uk/research-briefings/cbp-9958/" ],
  convention: [ "European Court of Human Rights: European Convention text", "https://www.echr.coe.int/documents/d/echr/convention_eng" ],
  court: [ "European Court of Human Rights: the Court in brief", "https://www.echr.coe.int/documents/d/echr/court_in_brief_eng" ],
  stats: [ "European Court of Human Rights: Analysis of Statistics 2025", "https://www.echr.coe.int/documents/d/echr/stats-analysis-2025-eng" ],
  hra: [ "UK legislation: Human Rights Act 1998", "https://www.legislation.gov.uk/ukpga/1998/42/contents" ],
  deportation: [ "Home Office: criminality and Article 8 cases", "https://www.gov.uk/government/publications/criminality-guidance-in-article-8-echr-cases/criminality-article-8-echr-cases-accessible" ],
  gfa: [ "House of Commons Library: Belfast/Good Friday Agreement", "https://commonslibrary.parliament.uk/research-briefings/cbp-9547/" ],
  coe: [ "Council of Europe: supervision of execution of judgments", "https://www.coe.int/en/web/execution" ]
}.freeze

ECHR_WITHDRAWAL_FACTS = FactBank.build([
  [ "What does ECHR stand for?",
    [ "European Convention on Human Rights", "European Council for Human Regulation", "European Charter of Home Rule", "European Court for Human Rights" ], 0,
    "The ECHR is the European Convention on Human Rights, an international treaty drafted after the Second World War.", :convention, 0, 1, "The expansion prevents basic institutional confusion but is only supporting knowledge." ],
  [ "Is the ECHR an institution of the European Union?",
    [ "Yes, it is an EU regulation", "No; it belongs to the separate Council of Europe system", "Only since Brexit", "Only for eurozone states" ], 1,
    "The Convention and Court belong to the Council of Europe, not the EU. Brexit did not withdraw the UK from the ECHR.", :commons, 0, 3, "Institutional independence from the EU is foundational to understanding the proposed withdrawal." ],
  [ "Which country helped draft the Convention and was among its first ratifiers?",
    [ "Only France", "The United States", "The United Kingdom", "No present member" ], 2,
    "British lawyers and politicians played an important role, and the UK was among the first states to ratify.", :commons, -1, 1, "Historical authorship is useful context but does not settle whether continued membership is advisable." ],
  [ "Which body decides individual applications alleging Convention violations?",
    [ "The Court of Justice of the European Union", "The UK Supreme Court alone", "The European Commission", "The European Court of Human Rights" ], 3,
    "The Strasbourg-based European Court of Human Rights decides applications under the Convention.", :court, 0, 2, "Identifying the actual adjudicator is significant to sovereignty arguments." ],
  [ "Which right is protected by Article 2?",
    [ "The right to life", "A right to own any weapon", "Automatic citizenship", "A right to avoid all taxation" ], 0,
    "Article 2 protects life and imposes both limits on lethal force and duties to protect and investigate.", :convention, -1, 2, "The substantive protection is significant to judging what external supervision covers." ],
  [ "Which treatment does Article 3 prohibit?",
    [ "Any prison sentence", "Torture and inhuman or degrading treatment", "All immigration detention", "Unpopular political speech" ], 1,
    "Article 3 prohibits torture and inhuman or degrading treatment.", :convention, -1, 3, "Article 3 is foundational because it is absolute and central to difficult removal cases." ],
  [ "May Article 3 torture protection be balanced away because a person committed a serious crime?",
    [ "Yes, after a four-year sentence", "Yes, by ministerial certificate", "No", "Only the receiving state decides" ], 2,
    "The Article 3 prohibition is absolute; danger posed by an individual does not permit removal to a real risk of torture.", :commons, 1, 3, "The absolute nature of Article 3 is foundational to both criticism and defence of the system." ],
  [ "What kind of right is Article 8 protection for private and family life?",
    [ "A right that always defeats deportation", "A right applying only to citizens", "An absolute right with no exceptions", "A qualified right permitting proportionate lawful interference" ], 3,
    "Article 8 permits interference that is lawful, necessary and proportionate for listed public interests, including public safety and preventing crime.", :convention, 0, 3, "The qualified structure is foundational to evaluating claims that family life automatically blocks removal." ],
  [ "Does Article 8 prevent the UK from deporting every foreign offender?",
    [ "No", "Yes", "Only where a sentence exceeds four years", "Only before conviction" ], 0,
    "UK law provides for deportation and sets strong public-interest rules; some cases succeed where statutory exceptions or very compelling circumstances apply.", :deportation, 1, 3, "The actual rather than caricatured effect on deportation is foundational." ],
  [ "What must applicants normally do before applying to the Strasbourg Court?",
    [ "Obtain permission from the UN", "Use effective domestic remedies", "Move to France", "Win a parliamentary vote" ], 1,
    "Applicants generally must give domestic courts the opportunity to resolve the alleged violation first.", :convention, -1, 2, "Exhaustion materially limits the Court's role as a first-instance tribunal." ],
  [ "Can anyone appeal to Strasbourg merely because they dislike a UK court's factual conclusion?",
    [ "Yes, it is a general fourth-instance appeal", "Yes, if the case was reported", "No; an arguable Convention violation is required", "No individuals can apply" ], 2,
    "The Court is not a general appeal court for errors of domestic fact or law; the complaint must fall within Convention rights and admissibility rules.", :court, -1, 2, "Admissibility is significant to assessing judicial reach." ],
  [ "What is the 'margin of appreciation'?",
    [ "A tax charged on judgments", "A compulsory damages formula", "A power belonging only to the EU", "Discretion left to national authorities in applying some Convention rights" ], 3,
    "The Court allows states a variable margin in areas where national authorities are better placed or European consensus is limited.", :court, -1, 2, "National discretion is a significant qualification to claims of uniform control." ],
  [ "How does the Human Rights Act affect UK courts?",
    [ "It lets them apply Convention rights in domestic proceedings", "It makes Strasbourg judgments Acts of Parliament", "It abolishes parliamentary sovereignty", "It transfers every trial abroad" ], 0,
    "The Human Rights Act incorporates specified Convention rights into domestic law and gives UK courts remedies against unlawful public-authority action.", :hra, -1, 3, "Domestic enforceability is foundational to both rights protection and constitutional objections." ],
  [ "Can a UK court strike down an Act of Parliament under the Human Rights Act?",
    [ "Always", "No; higher courts can issue a declaration of incompatibility", "Only the Strasbourg Court can repeal it", "Only devolved courts may do so" ], 1,
    "For primary Westminster legislation, a declaration signals incompatibility but leaves the law valid until Parliament chooses whether to amend it.", :hra, -1, 3, "Preserved parliamentary authority is foundational to the sovereignty debate." ],
  [ "What duty does section 6 of the Human Rights Act generally place on public authorities?",
    [ "To follow every newspaper editorial", "To ignore Acts of Parliament", "To act compatibly with Convention rights unless legislation prevents it", "To refer every decision to Strasbourg" ], 2,
    "It is generally unlawful for a public authority to act incompatibly with a Convention right, subject to the statutory-legislation exception.", :hra, 1, 2, "The operational constraint on government is significant." ],
  [ "Are final Strasbourg judgments in cases against the UK binding on the UK in international law?",
    [ "No, they are academic advice", "Only if Parliament votes unanimously", "Only judgments about trade", "Yes" ], 3,
    "Convention states undertake to abide by final judgments in cases to which they are parties.", :convention, 1, 3, "Binding external adjudication is foundational to the case for restored national control." ],
  [ "Who supervises states' implementation of Strasbourg judgments?",
    [ "The Council of Europe's Committee of Ministers", "The European Central Bank", "The UK Electoral Commission", "NATO" ], 0,
    "The Committee of Ministers supervises payment and individual or general measures needed to execute judgments.", :coe, 0, 1, "Enforcement machinery is supporting institutional knowledge." ],
  [ "What is a Rule 39 interim measure?",
    [ "A final criminal conviction", "An urgent temporary indication intended to prevent irreparable harm", "A new Convention article", "An EU budget rule" ], 1,
    "The Court may indicate urgent interim measures, most often where there is an imminent risk to life or ill-treatment.", :court, 1, 2, "Interim intervention is significant to migration controversy but exceptional." ],
  [ "Would withdrawing from the ECHR automatically repeal the Human Rights Act?",
    [ "Yes, treaties erase statutes", "Yes, after one court order", "No; Parliament would need to decide domestic-law changes", "No, because withdrawal is impossible" ], 2,
    "Treaty withdrawal and repeal or amendment of a UK statute are legally distinct, although retaining the Act unchanged would create anomalies.", :commons, 0, 3, "The distinction between international and domestic law is foundational to consequences." ],
  [ "How much notice does Article 58 require for withdrawal from the Convention?",
    [ "One week", "One month", "Two years", "Six months" ], 3,
    "A state may denounce the Convention after giving six months' notice.", :convention, 1, 2, "The formal route matters to feasibility and transition." ],
  [ "Would withdrawal erase responsibility for alleged violations committed before it took effect?",
    [ "No", "Yes, immediately", "Only criminal cases survive", "Only tax cases survive" ], 0,
    "Article 58 preserves responsibility for acts capable of constituting violations before withdrawal became effective.", :convention, -1, 2, "Continuing jurisdiction over earlier conduct materially limits immediate effects." ],
  [ "Would withdrawal remove every international human-rights obligation binding the UK?",
    [ "Yes, the ECHR is the only treaty", "No", "Only UN obligations would vanish", "Only customary law would vanish" ], 1,
    "The UK would remain bound by other treaties and customary international law, although their courts and enforcement mechanisms differ.", :commons, 0, 3, "Remaining obligations are foundational to realistic claims about regained freedom." ],
  [ "Where is commitment to the ECHR embedded in the Northern Ireland peace settlement?",
    [ "The Maastricht Treaty", "The NATO treaty", "The Belfast/Good Friday Agreement", "The Barnett formula" ], 2,
    "The Agreement committed the UK to incorporate the Convention and provide direct access to courts and remedies in Northern Ireland.", :gfa, -1, 3, "Northern Ireland obligations are foundational constitutional consequences." ],
  [ "Could ECHR withdrawal affect the UK's devolution arrangements?",
    [ "No, rights are absent from every settlement", "Only English councils are affected", "Only tax powers change", "Yes" ], 3,
    "Convention compliance is built into the competence rules for devolved institutions, so withdrawal would require difficult constitutional choices.", :commons, -1, 2, "Devolution consequences are significant but their eventual resolution would be political." ],
  [ "Which UK–EU agreement also refers to continued human-rights commitments?",
    [ "The Trade and Cooperation Agreement", "The Schengen Agreement", "The euro convergence rules", "The Common Agricultural Policy" ], 0,
    "The post-Brexit Trade and Cooperation Agreement links aspects of law-enforcement cooperation to human-rights commitments.", :commons, -1, 2, "Security-cooperation consequences are significant to the cost of withdrawal." ],
  [ "Would ECHR withdrawal itself end the UK's membership of the United Nations?",
    [ "Yes", "No", "Only Security Council membership", "Only peacekeeping membership" ], 1,
    "The UN and Council of Europe are separate organisations; withdrawal would not remove the UK from the UN.", :commons, 0, 1, "This prevents institutional confusion but is not central." ],
  [ "Do most applications reaching the Strasbourg Court result in a judgment finding a violation?",
    [ "Yes, almost all", "Exactly half", "No; many are inadmissible or struck out", "The Court publishes no totals" ], 2,
    "Court statistics show that many applications are disposed of without a merits judgment.", :stats, -1, 2, "The filtering rate significantly informs claims about caseload and access." ],
  [ "Can Parliament knowingly legislate contrary to a Convention right while the UK remains a member?",
    [ "No text can be enacted", "Only after a referendum", "Only devolved legislatures can", "Yes domestically, though doing so may breach international obligations" ], 3,
    "Parliament remains legally sovereign in domestic law, but incompatible legislation can place the UK in breach of its treaty obligations.", :hra, 1, 2, "The dual legal consequences are significant to the sovereignty trade-off." ],
  [ "What control would withdrawal most directly restore?",
    [ "Freedom from binding Strasbourg adjudication under this treaty", "Freedom from all domestic courts", "Power to leave the UN without notice", "Power to abolish common law automatically" ], 0,
    "Withdrawal would end future binding Strasbourg jurisdiction under the Convention after transition, subject to past cases and other international obligations.", :commons, 1, 3, "Ending external judicial supervision is the foundational benefit claimed by proponents." ],
  [ "What is the central policy trade-off?",
    [ "Choosing between Europe and the Atlantic", "Greater national control versus common external rights supervision and associated constitutional cooperation", "Choosing whether courts should exist", "Choosing whether rights have definitions" ], 1,
    "Withdrawal would increase freedom from this treaty and Court, while reducing an external rights guarantee and creating consequences for Northern Ireland, devolution and European cooperation.", :commons, 0, 1, "The synthesis identifies the judgement evidence informs without deciding it." ]
], ECHR_SOURCES)

# Keep the importance distribution selective: these consequences are material,
# but less fundamental than the treaty's rights, safeguards and jurisdiction.
[ 18, 21, 22 ].each do |index|
  ECHR_WITHDRAWAL_FACTS.fetch(index)[:importance_weight] = 2
end
[ 9, 17 ].each do |index|
  ECHR_WITHDRAWAL_FACTS.fetch(index)[:importance_weight] = 1
end

# Avoid encoding the correct response in answer length.
{
  1 => [ 0, "Yes; it is an institution created and governed entirely by European Union law" ],
  5 => [ 2, "All detention, prosecution and punishment following a criminal conviction" ],
  7 => [ 0, "An unqualified entitlement that defeats every competing public interest" ],
  9 => [ 2, "Ask Parliament and the United Nations to reconsider the case together" ],
  10 => [ 0, "Yes; it rehearses all evidence and corrects every domestic factual or legal error" ],
  11 => [ 1, "A fixed percentage added to every damages award made by an international court" ],
  12 => [ 3, "It transfers the final interpretation of every Act of Parliament to an overseas court" ],
  13 => [ 0, "Yes; any judge can permanently invalidate primary legislation without an appeal" ],
  14 => [ 3, "To refer every disputed administrative decision to the Strasbourg Court before acting" ],
  16 => [ 2, "The United Kingdom's Electoral Commission acting with the Supreme Court" ],
  17 => [ 0, "A final determination that permanently resolves the whole underlying application" ],
  19 => [ 0, "Twenty-four months followed by a mandatory referendum in every constituent nation" ],
  22 => [ 0, "The Maastricht Treaty establishing the institutions and citizenship of the European Union" ],
  24 => [ 2, "The euro convergence rules governing national deficits, debt and monetary policy" ],
  26 => [ 0, "Yes; nearly every lodged application proceeds to judgment and establishes a violation" ],
  27 => [ 1, "Only after both Houses approve the precise incompatibility by a two-thirds majority" ],
  28 => [ 3, "Power to repeal every domestic court judgment, statute and common-law rule automatically" ],
  29 => [ 3, "Choosing whether internationally recognised rights should have any legal definition at all" ]
}.each do |question_index, (option_index, text)|
  ECHR_WITHDRAWAL_FACTS.fetch(question_index)[:options][option_index] = text
end
