require_relative "fact_bank"

GAZA_SOURCES = {
  israel: [ "Israeli Ministry of Foreign Affairs: Two years since 7 October", "https://embassies.gov.il/cyprus/en/news/two-years-october-7-2023" ],
  idf_goals: [ "Israel Defense Forces: stated objectives in Gaza", "https://www.idf.il/en/mini-sites/israel-at-war/briefings-by-idf-spokesperson-bg-effie-defrin/may-25-press-briefings/press-briefing-by-idf-spokesperson-bg-effie-defrin-may-5-2025/" ],
  idf_results: [ "Israel Defense Forces: October 2025 ceasefire briefing", "https://www.idf.il/en/mini-sites/israel-at-war/briefings-by-idf-spokesperson-bg-effie-defrin/october-25-press-briefings/press-briefing-by-idf-spokesperson-bg-effie-defrin-october-10-2025/" ],
  idf_leaders: [ "Israel Defense Forces: reported effects on Hamas leadership", "https://www.idf.il/en/mini-sites/idf-press-releases-israel-at-war/april-25-pr/summary-of-the-renewed-operations-in-the-gaza-strip-major-achievements-of-the-idf-and-isa/" ],
  un_ceasefire: [ "United Nations: implementation of the October 2025 Gaza ceasefire", "https://digitallibrary.un.org/record/4096961/files/S_2025_807-EN.pdf" ],
  icrc_conduct: [ "International Committee of the Red Cross: conduct of hostilities", "https://www.icrc.org/en/law-and-policy/conduct-hostilities-and-protection-civilians" ],
  icrc_hospitals: [ "International Committee of the Red Cross: protection of hospitals", "https://www.icrc.org/en/document/protection-hospitals-during-armed-conflicts-what-law-says" ],
  icrc_hostages: [ "International Committee of the Red Cross: hostages held in Gaza", "https://www.icrc.org/en/document/FAQ-icrc-work-hostages-gaza" ],
  icj: [ "International Court of Justice: Order of 24 May 2024", "https://www.icj-cij.org/sites/default/files/case-related/192/192-20240524-ord-01-00-en.pdf" ],
  icc: [ "International Criminal Court: arrest warrants in the Situation in Palestine", "https://www.icc-cpi.int/news/situation-state-palestine-icc-pre-trial-chamber-i-rejects-state-israels-challenges" ],
  ohchr: [ "UN Human Rights Office: attacks in Gaza, October–December 2023", "https://www.ohchr.org/sites/default/files/documents/countries/opt/20240619-ohchr-thematic-report-indiscrim-disprop-attacks-gaza-oct-dec2023.pdf" ],
  ocha: [ "UN OCHA: Gaza reported impact snapshot, 24 June 2026", "https://www.ochaopt.org/sites/default/files/Gaza_Reported_Impact_Snapshot_24_June_2026.pdf" ],
  world_bank: [ "World Bank, UN and EU: Gaza Rapid Damage and Needs Assessment", "https://thedocs.worldbank.org/en/doc/e539cbf23b348c3d4fc69b8a7e9c9d7d-0280062026/rapid-damage-and-needs-assessment-gaza-strip-april-2026" ],
  ipc: [ "Integrated Food Security Phase Classification: Gaza special snapshot", "https://www.ipcinfo.org/fileadmin/user_upload/ipcinfo/docs/IPC_Gaza_Strip_Acute_Food_Insecurity_Malnutrition_Oct2025_Apr2026_Special_Snapshot.pdf" ],
  unga: [ "UN General Assembly: protection of civilians and humanitarian obligations", "https://www.un.org/unispal/document/resolution-protection-of-civilians-ga-es10-12jun25/" ]
}.freeze

GAZA_FACTS = FactBank.build([
  [ "Approximately how many people were killed in Israel during the Hamas-led attacks of 7 October 2023?",
    [ "More than 1,200", "About 120", "More than 12,000", "Fewer than 20" ], 0,
    "Israeli authorities report that more than 1,200 people were killed. Most were civilians, alongside members of the security forces and foreign nationals.", :israel, 1, 3,
    "The scale and character of the attack are foundational to assessing Israel's security justification for responding." ],
  [ "How many people were taken hostage into Gaza during the 7 October attacks?",
    [ "Fewer than 50", "251", "Approximately 600", "More than 1,000" ], 1,
    "Israeli authorities identify 251 people as having been abducted into Gaza on 7 October 2023.", :israel, 1, 3,
    "The hostage-taking created one of the campaign's two principal stated objectives." ],
  [ "Which pair did the Israeli military repeatedly describe as its principal Gaza war objectives?",
    [ "Annexing Gaza and closing the West Bank", "Replacing the Palestinian Authority and occupying Lebanon", "Returning hostages and dismantling Hamas", "Recovering Sinai and ending all regional diplomacy" ], 2,
    "The IDF stated that its intertwined objectives were returning the hostages and dismantling or decisively defeating Hamas's regime and military capability.", :idf_goals, 1, 3,
    "A campaign's gains cannot be judged without identifying the objectives against which Israel asked for it to be assessed." ],
  [ "How does international humanitarian law treat the taking of civilian hostages?",
    [ "It is lawful when intended to exchange prisoners", "It is permitted for seven days", "It is governed only by domestic criminal law", "It is prohibited" ], 3,
    "Hostage-taking is prohibited. Those holding hostages must treat them humanely, while the ICRC calls for their immediate and unconditional release.", :icrc_hostages, 1, 2,
    "The legal and human significance of hostage-taking is foundational to the case for securing their release." ],
  [ "What does the international humanitarian-law rule of distinction require?",
    [ "Separating civilians from military objectives", "Using identical weapons against every target", "Ending a war whenever civilians remain nearby", "Treating every government facility as military" ], 0,
    "Parties must distinguish civilians and civilian objects from combatants and military objectives, and may direct attacks only against military objectives.", :icrc_conduct, -1, 3,
    "Distinction is foundational to assessing a campaign fought in densely populated areas." ],
  [ "In the law governing attacks, what does 'proportionality' principally compare?",
    [ "Total deaths on each side of the whole war", "Civilian harm against military advantage", "A state's population against its opponent's population", "The cost of weapons against reconstruction spending" ], 1,
    "Legal proportionality is generally assessed attack by attack. It prohibits expected incidental civilian harm excessive in relation to the concrete and direct military advantage anticipated; it is not a requirement that the two sides suffer equal casualties.", :icrc_conduct, 0, 3,
    "This distinction prevents the site's broader word 'justified' from being mistaken for a verdict on every individual attack." ],
  [ "Does a legitimate military objective automatically make any amount of civilian harm lawful?",
    [ "Yes, once self-defence is invoked", "Yes, if warnings were issued first", "No; distinction, proportionality and feasible precautions still apply", "No, because military objectives may never be attacked" ], 2,
    "The existence of a military objective does not displace the rules protecting civilians. Attackers must still distinguish, assess proportionality and take feasible precautions.", :icrc_conduct, -1, 2,
    "The continuing protection of civilians is foundational to weighing means against ends." ],
  [ "If a defending force unlawfully uses civilians as human shields, what happens to the attacker's obligations toward those civilians?",
    [ "The civilians automatically become combatants", "Every nearby object becomes a lawful target", "Only the defending force retains legal duties", "The attacker's obligations remain" ], 3,
    "Using human shields is prohibited, but it does not remove the opposing party's duties of distinction, proportionality and precautions toward the civilians involved.", :icrc_conduct, 0, 2,
    "Responsibility for one party's violation does not erase the other's independent duties." ],
  [ "What is the normal legal status of a functioning civilian hospital during armed conflict?",
    [ "It has special protection from attack", "It is always a military objective", "It may be attacked whenever soldiers receive treatment", "Its status depends only on who owns the land" ], 0,
    "Hospitals and medical units receive special protection. That protection can cease only under restricted conditions when a facility is used for acts harmful to the enemy outside its humanitarian function.", :icrc_hospitals, -1, 2,
    "Hospital protection is significant because damage to health care creates direct and cascading civilian harm." ],
  [ "If a hospital loses its special protection because it is used for harmful military acts, which rule still applies to an attack?",
    [ "The hospital may be destroyed without further assessment", "Proportionality and feasible precautions still apply", "Only a vote of the UN General Assembly is required", "All patients acquire combatant status" ], 1,
    "Loss of special protection is not a blank cheque. The attacker must still assess proportionality, take feasible precautions and consider the wider effect on medical care.", :icrc_hospitals, 0, 2,
    "This qualification is significant to evaluating competing claims about military use of medical facilities." ],
  [ "What did the International Court of Justice decide at the provisional-measures stage of South Africa v Israel?",
    [ "That every alleged crime had been proved beyond reasonable doubt", "That Israel had won the case on the merits", "That plausible rights under the Genocide Convention faced a risk of irreparable prejudice requiring interim measures", "That the Court had no power to issue any order" ], 2,
    "The ICJ indicated binding provisional measures to protect rights it found plausible pending a final decision. It did not at that stage decide that genocide had occurred.", :icj, -1, 2,
    "Understanding the procedural status avoids both dismissing the Court's intervention and misreporting it as a final judgment." ],
  [ "Did the ICJ's 2024 provisional-measures orders constitute a final judgment that Israel had committed genocide?",
    [ "Yes, with criminal sentences imposed", "Yes, but only for northern Gaza", "No, because genocide is outside the Court's jurisdiction", "No; the merits had not been finally decided" ], 3,
    "Provisional measures address urgent risk while litigation continues. They are legally important but are not a final merits judgment or a criminal conviction.", :icj, 0, 1,
    "The distinction is significant because the claim is frequently misstated in opposite directions." ],
  [ "What evidential threshold did the ICC use when issuing arrest warrants for Benjamin Netanyahu and Yoav Gallant in November 2024?",
    [ "Reasonable grounds to believe", "Proof beyond reasonable doubt after trial", "A simple majority vote of UN members", "No evidential threshold at all" ], 0,
    "The Pre-Trial Chamber found reasonable grounds to believe that alleged war crimes and crimes against humanity fell within the warrants. Issuing a warrant is not a conviction.", :icc, -1, 1,
    "The warrants are material evidence of judicial concern, while their preliminary character must remain clear." ],
  [ "Who supplied the cumulative Palestinian fatality figure reproduced in OCHA's June 2026 Gaza impact snapshot?",
    [ "The World Bank", "The Israeli Supreme Court", "The Gaza Ministry of Health", "The International Committee of the Red Cross" ], 2,
    "OCHA attributes the reported Gaza fatality total to the Ministry of Health in Gaza and expressly labels figures not yet verified by the UN according to their source.", :ocha, 0, 1,
    "Source attribution is significant because repeating a figure is not the same as independently verifying every underlying record." ],
  [ "Did the headline Gaza fatality total itself classify every person killed as either civilian or combatant?",
    [ "Yes, using four military ranks", "Yes, after an ICC trial for every name", "Only fatalities outside hospitals were classified", "No; the total did not itself provide that complete classification" ], 3,
    "The reported aggregate does not itself separate every civilian from every combatant. Identified demographic categories and separate combatant claims provide relevant but incomplete information.", :ocha, 0, 1,
    "This limitation matters to casualty-ratio arguments without making the deaths or identified demographic data disappear." ],
  [ "As of 31 December 2025, how many Palestinian fatalities did OCHA's cited breakdown identify by name or demographic category?",
    [ "71,444", "Approximately 7,100", "More than 700,000", "Fewer than 1,200" ], 0,
    "OCHA's June 2026 snapshot records 71,444 identified fatalities as of 31 December 2025, within a higher cumulative total reported by Gaza's Ministry of Health.", :ocha, -1, 3,
    "The identified toll is foundational to understanding the human cost even while classification and verification questions remain." ],
  [ "What pattern did OHCHR report among the Gaza fatalities it had verified for selected incidents in the early campaign?",
    [ "Nearly all occurred in incidents with one fatality", "A large majority occurred in incidents killing at least five people", "None occurred in residential buildings", "Every verified fatality was a combatant" ], 1,
    "OHCHR reported that 87 per cent of the fatalities it had verified occurred in incidents causing five or more deaths, raising concern about wide-area effects in densely populated places.", :ohchr, -1, 2,
    "The concentration of fatalities is significant evidence about methods and foreseeable civilian risk, though it is not alone a legal ruling on each strike." ],
  [ "By October 2025, what proportion of Gaza's housing units did the UN–EU–World Bank assessment classify as damaged or destroyed?",
    [ "About one tenth", "Approximately one third", "About 76.6 per cent", "Every housing unit without exception" ], 2,
    "The assessment estimated that 371,888 of 485,361 housing units—76.6 per cent—were damaged or destroyed.", :ocha, -1, 3,
    "The scale of housing loss is foundational to weighing the campaign's lasting civilian cost." ],
  [ "What did OHCHR report about projectiles fired from Gaza toward Israel during the campaign?",
    [ "They were used only for illumination", "Every projectile struck a military base", "No projectiles were fired after 7 October", "Indiscriminate projectile fire continued" ], 3,
    "OHCHR reported that Palestinian armed groups continued firing projectiles toward Israel that were inherently indiscriminate, in violation of international humanitarian law.", :ohchr, 1, 1,
    "Continued attacks on Israeli population areas are relevant to the security threat the campaign sought to suppress." ],
  [ "What did the 2026 joint assessment estimate for Gaza's recovery and reconstruction needs?",
    [ "Approximately US$71.5 billion", "Less than US$1 billion", "Exactly US$8 billion", "More than US$700 billion" ], 0,
    "The World Bank, UN and EU estimated recovery and reconstruction needs at about US$71.5 billion for damage and losses incurred through October 2025.", :world_bank, -1, 2,
    "The estimate gives material scale to consequences extending far beyond immediate casualties." ],
  [ "What effect did the IDF say its campaign had on Hamas's senior leadership?",
    [ "No senior figures were affected", "Leadership losses disrupted command", "Every Hamas member surrendered", "Leadership was transferred to the Palestinian Authority" ], 1,
    "The IDF reported killing senior political and military figures and described this as disrupting Hamas's governance and coordination. This is an Israeli operational assessment, not an independently complete measure of Hamas's remaining capability.", :idf_leaders, 1, 2,
    "Leadership losses are a significant claimed military gain, while attribution and the difference between disruption and elimination remain important." ],
  [ "What did the IPC conclude about food conditions after the October 2025 ceasefire improved access?",
    [ "Food insecurity ended immediately", "Every household had normal market access", "Famine conditions were offset, but the situation remained critical", "The IPC withdrew all analysis as impossible" ], 2,
    "The IPC found that improved access after the ceasefire offset famine conditions, while acute food insecurity and malnutrition remained critical and vulnerable to renewed disruption.", :ipc, -1, 2,
    "Both the severity of deprivation and its responsiveness to access are foundational to assessing foreseeable humanitarian harm." ],
  [ "Under international humanitarian law, may food indispensable to civilians be withheld for the purpose of starving them?",
    [ "Yes, whenever hostages are held", "Yes, if a border crossing is privately operated", "Only after thirty days' notice", "No; starvation of civilians as a method of warfare is prohibited" ], 3,
    "Starvation of civilians as a method of warfare is prohibited. Security screening of aid does not remove duties to permit and facilitate humanitarian relief subject to lawful controls.", :icrc_conduct, -1, 2,
    "Protection of civilian subsistence is foundational when judging siege and access policies." ],
  [ "What did Israeli reporting say its forces found and attacked beneath Gaza during the campaign?",
    [ "An extensive tunnel and underground military network", "A natural cave system with no claimed military use", "Only civilian railway tunnels", "No underground structures at all" ], 0,
    "Israel reported discovering and destroying numerous tunnel shafts, passages, command sites and other underground infrastructure used by Hamas. The precise extent and effect rely substantially on Israeli military reporting.", :idf_results, 1, 2,
    "Hamas's embedded underground capability is significant to the military-necessity case, while the provenance of operational claims should remain visible." ],
  [ "How did the October 2025 agreement provide for the release of the final 20 living Israeli hostages?",
    [ "Through unilateral battlefield rescues", "Through a negotiated ceasefire and exchange arrangement", "Through an ICJ criminal sentence", "Through their transfer to a third war zone" ], 1,
    "The UN reports that the parties and mediators agreed implementation steps linking a ceasefire, partial Israeli withdrawal, aid entry, hostage release and release of Palestinian prisoners and detainees. Hamas released the final 20 living hostages on 13 October.", :un_ceasefire, 1, 3,
    "How the remaining hostages returned is foundational to judging the respective contributions of military pressure and negotiation." ],
  [ "At the start of the October 2025 ceasefire, how many hostages—living and dead—did Israel say remained to be returned?",
    [ "Eight", "Twenty", "Forty-eight", "Two hundred and fifty-one" ], 2,
    "The IDF stated that the agreement concerned the return of 48 remaining hostages, including living people and the remains of those who had died.", :idf_results, 0, 1,
    "The figure clarifies both progress before the final agreement and the objective still outstanding when operations stopped." ],
  [ "Did warnings or evacuation instructions by themselves remove civilian status from people who stayed behind?",
    [ "Yes, after any text message", "Yes, unless they possessed a foreign passport", "Only when a warning named a specific building", "No; civilians remain protected unless and for such time as they directly participate in hostilities" ], 3,
    "Warnings can be an important precaution, but inability or unwillingness to leave does not by itself turn a civilian into a combatant or remove other protections.", :icrc_conduct, 0, 2,
    "This distinction is significant when assessing strikes after mass evacuation orders." ],
  [ "Can a campaign-wide civilian-to-combatant casualty ratio, by itself, determine whether each attack complied with proportionality law?",
    [ "No; the legal assessment depends on information and anticipated advantage and harm for particular attacks", "Yes; any ratio above one is automatically unlawful", "Yes; national population totals decide the result", "No, because civilian casualties are legally irrelevant" ], 0,
    "Aggregate ratios may be evidence about patterns, but legal proportionality ordinarily turns on what was reasonably anticipated for a particular attack, not solely on the eventual campaign-wide ratio.", :icrc_conduct, 0, 2,
    "The question guards against a common statistical shortcut without treating aggregate patterns as irrelevant." ],
  [ "Can evidence that Hamas committed war crimes legally excuse separate violations by Israeli forces, or vice versa?",
    [ "Yes, because the first violation suspends humanitarian law", "No; each party remains responsible for its own conduct", "Only the larger party retains obligations", "Only conduct after a ceasefire can be examined" ], 1,
    "International humanitarian law binds all parties independently. Hamas's attacks, hostage-taking or use of civilian areas cannot legalize an unlawful Israeli attack; Israeli violations cannot legalize attacks on Israeli civilians.", :unga, 0, 3,
    "Independent responsibility is foundational to an informed judgement that neither minimizes 7 October nor treats it as unlimited authorization." ],
  [ "Which conclusion is factual evidence alone capable of establishing about the proposition on this page?",
    [ "That every reasonable person must select the same opinion", "That moral judgement is unnecessary once casualty totals are known", "The relevant gains, harms, uncertainties and legal constraints—not a uniquely compelled moral weighting of them", "That none of the documented events can inform an opinion" ], 2,
    "Evidence can correct false premises and clarify consequences, causal claims and legal constraints. Whether the gains justified the civilian harm also requires a moral and political judgement about necessity, alternatives, risk and proportionality in the broader ordinary-language sense.", :icrc_conduct, 0, 1,
    "The final supporting question makes the boundary between demonstrated knowledge and legitimate value judgement explicit." ]
], GAZA_SOURCES)
