require_relative "fact_bank"

MINIMUM_WAGE_SOURCES = {
  dol: [ "US Department of Labor", "https://www.dol.gov/agencies/whd/minimum-wage" ],
  dol_guide: [ "US Department of Labor: Minimum Wage and Overtime Pay", "https://webapps.dol.gov/elaws/elg/minwage.htm" ],
  bls: [ "US Bureau of Labor Statistics: Minimum Wage Workers, 2024", "https://www.bls.gov/opub/reports/minimum-wage/2024/home.htm" ],
  cbo: [ "Congressional Budget Office: The Effects on Employment and Family Income", "https://www.cbo.gov/publication/55681" ],
  cbo_budget: [ "Congressional Budget Office: Raise the Wage Act of 2021", "https://www.cbo.gov/publication/56975" ],
  crs: [ "Congressional Research Service: State Minimum Wages", "https://www.congress.gov/crs-product/R43792" ],
  cpi: [ "US Bureau of Labor Statistics: CPI Inflation Calculator", "https://www.bls.gov/data/inflation_calculator.htm" ],
  nber: [ "National Bureau of Economic Research: Minimum Wages and Employment", "https://www.nber.org/papers/w12663" ],
  irle: [ "UC Berkeley IRLE: Minimum Wage Effects", "https://irle.berkeley.edu/publications/working-papers/minimum-wage-effects-across-state-borders/" ],
  gao: [ "US Government Accountability Office: Low-Wage Workers", "https://www.gao.gov/products/gao-21-45" ]
}.freeze

MINIMUM_WAGE_FACTS = FactBank.build([
  [ "What is the standard federal minimum wage for covered non-exempt workers?",
    [ "$7.25 per hour", "$2.13 per hour", "$10.50 per hour", "$15.00 per hour" ], 0,
    "The standard federal floor has been $7.25 since July 2009. $2.13 is the minimum direct cash wage where a lawful tip credit is used.", :dol_guide, 1, 3,
    "The existing legal baseline is foundational to judging the scale and reach of the proposed increase." ],
  [ "When did the federal minimum wage last increase?",
    [ "1997", "2009", "2015", "2024" ], 1,
    "The final step of the last legislated federal increase took effect on 24 July 2009.", :bls, 1, 2,
    "The duration of the freeze materially affects arguments about lost purchasing power." ],
  [ "If federal and state minimum wages differ, which generally applies to a worker covered by both laws?",
    [ "Always the federal rate", "Always the state rate", "The higher applicable rate", "The average of the two" ], 2,
    "Covered workers are generally entitled to the highest applicable federal, state or local minimum.", :crs, 0, 3,
    "This determines which workers would actually receive a raise from a new federal floor." ],
  [ "Under current federal law, what minimum direct cash wage may an employer using the full tip credit pay a tipped worker?",
    [ "$0", "$7.25", "$4.25", "$2.13 per hour" ], 3,
    "The federal cash-wage floor is $2.13, but tips plus cash wages must reach the full applicable minimum and the employer must make up a shortfall.", :dol_guide, 0, 2,
    "Tipped-work rules identify an important group whose treatment can change a proposal's effects." ],
  [ "In 2024, what share of hourly paid US workers earned at or below the federal minimum wage?",
    [ "About 1%", "About 10%", "About 25%", "About 40%" ], 0,
    "BLS counted roughly 1% of hourly paid workers at or below $7.25; many low-paid workers earned above that old federal threshold.", :bls, -1, 2,
    "The directly observed federal-minimum group helps distinguish the current floor from the wider group affected by $15." ],
  [ "Which group is excluded from BLS's count of hourly workers paid at or below the federal minimum?",
    [ "Part-time hourly workers", "Salaried and other non-hourly workers", "Workers aged 25 and over", "Private-sector workers" ], 1,
    "The published series covers workers reporting hourly rates; it excludes salaried and other non-hourly workers.", :bls, 0, 1,
    "This is a measurement limitation rather than a central policy effect." ],
  [ "What happens to a fixed $7.25 wage's purchasing power when consumer prices rise?",
    [ "It rises automatically", "It is unchanged in real terms", "It falls", "It doubles" ], 2,
    "Without nominal adjustment, inflation reduces the quantity of goods and services the wage can buy.", :cpi, 1, 3,
    "Real purchasing power is a central reason offered for raising a long-frozen nominal wage." ],
  [ "Does current federal law automatically index the $7.25 minimum wage to inflation?",
    [ "Yes, monthly", "Yes, annually", "Only during recessions", "No; Congress must change it" ], 3,
    "The federal rate is statutory and has no automatic inflation adjustment, unlike indexed rates in many states.", :crs, 1, 2,
    "Indexation explains why the federal rate can remain fixed despite price changes." ],
  [ "How many states and the District of Columbia had rates above $7.25 under the CRS's 2024 review?",
    [ "30 states and DC", "5 states", "All 50 states", "No states" ], 0,
    "CRS reported rates above the federal floor in 30 states and DC.", :crs, -1, 2,
    "Existing state laws substantially limit the geographic reach of a federal increase." ],
  [ "In states with no state minimum-wage law, what protects most covered workers?",
    [ "No wage floor applies", "The federal FLSA floor", "A voluntary industry code", "The median state wage" ], 1,
    "Most workers in those states remain covered by the federal Fair Labor Standards Act.", :crs, 1, 2,
    "This identifies where the federal floor is especially consequential." ],
  [ "What did CBO project a large federal minimum-wage increase would do to earnings of many low-wage workers who remain employed?",
    [ "Reduce them", "Leave them unchanged", "Increase them", "Replace wages entirely with benefits" ], 2,
    "CBO projected higher earnings for many affected workers whose jobs and hours remain.", :cbo, 1, 3,
    "Higher earnings are the proposal's principal intended benefit." ],
  [ "What employment effect did CBO also project from a sufficiently large increase?",
    [ "Guaranteed job growth for every industry", "No possible employment response", "An exact loss known with certainty", "Some reduction in employment, with substantial uncertainty about its size" ], 3,
    "CBO projected fewer jobs than under current law while emphasising uncertainty around the estimate.", :cbo, -1, 3,
    "Possible job loss is the proposal's principal economic cost and therefore foundational." ],
  [ "How can a higher minimum wage reduce measured poverty?",
    [ "By raising family income for some low-paid workers", "By redefining the poverty line", "By eliminating taxes", "By guaranteeing every adult a job" ], 0,
    "Higher wages can lift some families above poverty thresholds, though effects depend on employment, hours and family circumstances.", :cbo, 1, 3,
    "Poverty reduction is a central claimed policy outcome." ],
  [ "Why do minimum-wage increases not target only households below the poverty line?",
    [ "Every minimum-wage worker is a child", "Workers' hourly wages do not reveal total family income", "The poverty line excludes wages", "Only unemployed people are poor" ], 1,
    "A low-paid worker may live with higher earners, while many poor households have no employed minimum-wage worker.", :cbo, -1, 2,
    "Targeting efficiency is significant when comparing the policy with tax credits or transfers." ],
  [ "Which business response can offset part of a mandated wage increase?",
    [ "Federal cancellation of rent", "Automatic productivity decline", "Higher prices", "A ban on automation" ], 2,
    "Firms may absorb costs through profits or productivity, reduce employment or hours, or pass some costs into prices.", :cbo, -1, 3,
    "Price pass-through affects consumers and the real value of workers' gains." ],
  [ "What is a wage 'spillover' from a minimum-wage increase?",
    [ "Workers moving across a state border", "Tips being shared", "Wages falling below zero", "Pay rises for workers initially above the new floor as wage structures adjust" ], 3,
    "Employers may raise wages somewhat above the statutory floor to preserve pay differentials or retain staff.", :crs, 1, 2,
    "Spillovers broaden both the benefits and employer costs beyond workers initially below $15." ],
  [ "At 40 paid hours per week for 52 weeks, what gross annual pay does $15 per hour produce?",
    [ "$31,200", "$15,000", "$62,400", "$7,250" ], 0,
    "The arithmetic is $15 × 40 × 52 = $31,200 before tax and assuming all hours are paid.", :dol, 0, 2,
    "Annualising the proposal makes its income scale understandable, though actual hours vary." ],
  [ "Would a $15 federal floor necessarily raise the wage of someone already legally earning $18 per hour?",
    [ "Yes, to $30", "No, not directly", "Yes, but only in rural areas", "No, because federal law would lower it" ], 1,
    "The legal requirement directly binds wages below $15; an $18 worker might receive an indirect spillover but is not guaranteed one.", :crs, 0, 1,
    "This clarifies the direct scope of the proposition." ],
  [ "Why can one national dollar rate have different effects across regions?",
    [ "Federal dollars have different legal values", "Hours contain different numbers of minutes", "Wage levels and living costs vary geographically", "State borders stop inflation" ], 2,
    "A $15 floor is closer to prevailing wages in high-wage areas and more binding in lower-wage areas.", :cbo, -1, 3,
    "Regional variation is central to judging a uniform national floor." ],
  [ "Can an employer lawfully satisfy the minimum wage with tips alone while paying no direct cash wage under the federal tip-credit rules?",
    [ "Yes, in every state", "Yes, with oral permission", "Only on weekends", "No; at least the federal direct cash wage is required" ], 3,
    "Federal law requires at least $2.13 in direct cash wages where the tip credit is claimed, plus enough total compensation to reach the full floor.", :dol_guide, 0, 1,
    "This is an implementation detail relevant to tipped workers." ],
  [ "What special federal youth wage may apply during a worker's first 90 consecutive calendar days before age 20?",
    [ "$4.25 per hour", "$2.13 per hour", "$7.25 plus tips", "$15 per hour" ], 0,
    "Federal law permits $4.25 in limited circumstances and prohibits displacing other workers to use it.", :dol_guide, 0, 1,
    "A youth exception is narrower than the approved proposition's adult-worker scope." ],
  [ "Which workers are generally covered by the approved proposition's wording?",
    [ "Only tipped workers", "Non-tipped adult workers covered by federal minimum-wage law", "Every self-employed contractor", "Only federal employees" ], 1,
    "The wording deliberately excludes tipped and youth subminimum categories and does not convert independent contractors into employees.", :dol_guide, 0, 3,
    "Precisely identifying the covered population is foundational to interpreting the proposition." ],
  [ "What research design compares employment changes in adjacent counties on opposite sides of state borders?",
    [ "A national opinion poll", "A laboratory experiment with no workers", "A border-pair natural experiment", "A company annual report" ], 2,
    "Border studies compare nearby labour markets exposed to different minimum-wage policies to reduce confounding geographic differences.", :irle, 0, 2,
    "Understanding credible causal designs is significant because empirical estimates disagree." ],
  [ "Do all credible minimum-wage studies produce the same employment estimate?",
    [ "Yes, exactly zero", "Yes, exactly minus 10%", "Yes, exactly plus 10%", "No; estimates vary with data, setting, method and policy size" ], 3,
    "The literature contains estimates ranging from little detectable effect to meaningful job loss; extrapolating beyond studied increases adds uncertainty.", :nber, 0, 3,
    "Uncertainty and disagreement in the central evidence must inform confidence in either policy position." ],
  [ "Which sector employs a relatively large share of workers at or below the federal minimum?",
    [ "Leisure and hospitality", "Aerospace manufacturing", "Utilities", "Software publishing" ], 0,
    "BLS data show a high concentration in leisure and hospitality, including food services.", :bls, 0, 2,
    "Industry concentration helps identify where benefits, prices and employment adjustments may occur." ],
  [ "Are workers at or below the federal minimum predominantly full-time in BLS data?",
    [ "Yes, virtually all", "No; part-time work is disproportionately common", "Full- and part-time status is legally identical", "BLS excludes part-time workers" ], 1,
    "Part-time workers are more likely than full-time workers to report hourly earnings at or below the federal minimum.", :bls, 0, 2,
    "Hours worked affect annual income gains and the population affected." ],
  [ "If employers reduce scheduled hours after an hourly raise, what determines a worker's weekly earnings change?",
    [ "Only the new hourly rate", "Only the old hourly rate", "Both the wage increase and the hours change", "The worker's age alone" ], 2,
    "Weekly earnings equal hourly pay multiplied by paid hours, so a higher rate can be partly offset by fewer hours.", :cbo, -1, 3,
    "Total earnings, not the hourly rate alone, determine the proposal's material benefit." ],
  [ "How can higher wages affect federal means-tested benefit spending?",
    [ "They can never affect eligibility", "They automatically abolish programs", "They always increase every benefit", "Higher family income can reduce some benefits, while job loss can increase them" ], 3,
    "CBO models both reduced eligibility from higher earnings and increased need among people whose employment falls.", :cbo_budget, 0, 2,
    "Fiscal and household interactions are significant secondary effects." ],
  [ "What did GAO find about many working adults receiving Medicaid or food assistance?",
    [ "They were concentrated in low-wage occupations and industries", "They were all unemployed", "They were all self-employed", "None worked for private employers" ], 0,
    "GAO found millions of adult wage earners in Medicaid or SNAP, often in low-wage sectors.", :gao, 1, 2,
    "Public-benefit participation bears on claims that low wages shift costs to taxpayers." ],
  [ "What is the most defensible conclusion about a $15 federal minimum from existing evidence?",
    [ "It has benefits but literally no trade-offs", "It would raise many wages, while employment, prices and regional effects remain important and uncertain", "It must eliminate every low-wage job", "State evidence is irrelevant to federal policy" ], 1,
    "Major assessments find meaningful income gains alongside possible employment losses and other adjustments; magnitudes depend on timing and economic conditions.", :cbo, 0, 3,
    "A balanced synthesis of the principal benefits, costs and uncertainty is foundational to an informed judgement." ]
], MINIMUM_WAGE_SOURCES)
