require_relative "fact_bank"

NUCLEAR_POWER_SOURCES = {
  gov: [ "UK Government: Nuclear energy", "https://www.gov.uk/government/policies/nuclear-energy" ],
  desnz: [ "DESNZ Public Attitudes Tracker, Spring 2026", "https://www.gov.uk/government/statistics/desnz-public-attitudes-tracker-spring-2026/desnz-public-attitudes-tracker-energy-infrastructure-and-energy-security-spring-2026-uk" ],
  digest: [ "DESNZ: Digest of UK Energy Statistics", "https://www.gov.uk/government/collections/digest-of-uk-energy-statistics-dukes" ],
  ipcc: [ "IPCC AR6: Energy Systems", "https://www.ipcc.ch/report/ar6/wg3/chapter/chapter-6/" ],
  iea: [ "International Energy Agency: Nuclear Power", "https://www.iea.org/energy-system/electricity/nuclear-power" ],
  ons: [ "Office for Nuclear Regulation: What we regulate", "https://www.onr.org.uk/our-work/what-we-regulate/" ],
  nda: [ "Nuclear Decommissioning Authority: Radioactive waste", "https://www.gov.uk/government/organisations/nuclear-decommissioning-authority" ],
  naog: [ "National Audit Office: Hinkley Point C", "https://www.nao.org.uk/reports/hinkley-point-c/" ],
  naa: [ "National Audit Office: Nuclear power in the UK", "https://www.nao.org.uk/insights/nuclear-power-in-the-uk/" ],
  iaea: [ "International Atomic Energy Agency: Nuclear power and climate change", "https://www.iaea.org/topics/nuclear-power-and-climate-change" ]
}.freeze

NUCLEAR_POWER_FACTS = FactBank.build([
  [ "What happens to most of the UK's existing nuclear generating capacity by the end of this decade under current closure schedules?",
    [ "It retires", "It becomes coal-fired", "It moves overseas", "It doubles automatically" ], 0,
    "The ageing Advanced Gas-cooled Reactor fleet is closing, leaving a replacement question even as Sizewell B continues.", :naa, 1, 3,
    "The scale and timing of retiring capacity are foundational to the replacement proposition." ],
  [ "During operation, how much carbon dioxide does a nuclear reactor emit from generating electricity?",
    [ "More than unabated coal", "Very little directly", "Exactly the same as gas", "Only when wind blows" ], 1,
    "Fission does not burn carbon fuel; lifecycle emissions arise mainly from construction, mining, enrichment and decommissioning.", :ipcc, 1, 3,
    "Operational and lifecycle emissions are central to nuclear power's climate case." ],
  [ "How do median lifecycle greenhouse-gas emissions from nuclear compare with fossil-fuel generation in IPCC assessments?",
    [ "Higher than coal", "Higher than gas", "Much lower", "Impossible to estimate at all" ], 2,
    "Lifecycle studies place nuclear in the low-carbon group alongside renewables, far below coal and gas without carbon capture.", :ipcc, 1, 3,
    "Lifecycle emissions directly bear on whether replacement supports climate goals." ],
  [ "What does 'firm' generation mean in electricity planning?",
    [ "Electricity sold only to businesses", "A plant immune to all outages", "Power with a fixed price", "Capacity expected to be available when needed, subject to outages" ], 3,
    "Firm capacity contributes during periods of system need; maintenance and unplanned faults mean it is not perfectly available.", :iea, 1, 3,
    "Firm low-carbon supply is a central claimed system benefit." ],
  [ "What has historically characterised UK nuclear capacity factors?",
    [ "High output over much of the year", "Generation only at noon", "Operation only when gas prices rise", "Zero planned maintenance" ], 0,
    "Nuclear stations typically run for long periods at high output, interrupted by refuelling, maintenance and faults.", :digest, 1, 2,
    "Actual utilisation determines how much retiring capacity replacement can supply." ],
  [ "Can conventional large nuclear stations rapidly vary output as cheaply and flexibly as all other balancing resources?",
    [ "Yes, without limits", "Not generally; they are usually operated as high-output baseload plant", "They cannot change output at all", "Only during winter" ], 1,
    "Reactors can load-follow technically, but UK economics generally favour sustained output; flexible demand, storage and other generation balance variation.", :iea, -1, 2,
    "Operational flexibility is significant in a renewables-heavy electricity system." ],
  [ "What is the principal long-lived waste-management challenge from nuclear power?",
    [ "Carbon ash", "Methane leakage", "Safely isolating high-level radioactive waste and spent fuel", "Disposable wind blades" ], 2,
    "Some radioactive materials require secure management over very long timescales.", :nda, -1, 3,
    "Long-term waste stewardship is a central cost and intergenerational obligation." ],
  [ "Does the UK currently have an operating geological disposal facility for its highest-activity waste?",
    [ "Yes, under every station", "Yes, opened in 1950", "Waste needs no disposal", "No; site-selection and development remain under way" ], 3,
    "Higher-activity waste is stored pending a planned geological disposal facility.", :nda, -1, 3,
    "The unresolved final-disposal route is foundational to judging further waste creation." ],
  [ "Who regulates nuclear safety and security at licensed UK nuclear sites?",
    [ "The Office for Nuclear Regulation", "Electricity retailers", "Local estate agents", "The International Energy Agency" ], 0,
    "ONR is the independent statutory regulator for nuclear safety, security, safeguards and transport.", :ons, 1, 2,
    "Independent regulation materially affects the probability and consequences of failures." ],
  [ "Does regulatory approval make a severe nuclear accident physically impossible?",
    [ "Yes", "No; it reduces and manages risk but cannot make it zero", "Only overseas", "Only for new reactors" ], 1,
    "Defence-in-depth lowers accident likelihood and consequences, but no complex technology has zero risk.", :ons, -1, 3,
    "Low-probability, high-consequence risk is central to the policy judgement." ],
  [ "Which two accidents most shaped modern public concern about civil nuclear safety?",
    [ "Three Mile Island and Deepwater Horizon", "Bhopal and Buncefield", "Chernobyl and Fukushima Daiichi", "Grenfell and Piper Alpha" ], 2,
    "Chernobyl involved a reactor explosion and fire; Fukushima followed earthquake, tsunami and loss of cooling.", :iaea, -1, 2,
    "Historical accident experience informs safety design and public risk tolerance." ],
  [ "What was the immediate trigger of the Fukushima Daiichi core damage?",
    [ "Normal refuelling", "A cyberattack", "Wind-power failure", "Loss of electrical power and cooling after earthquake and tsunami" ], 3,
    "Flooding disabled power and cooling following the natural disaster.", :iaea, -1, 2,
    "Understanding the causal chain supports informed comparison with UK hazards and designs." ],
  [ "What has been a recurring feature of recent European large-reactor projects?",
    [ "Long construction delays and cost overruns", "Completion in weeks", "No financing costs", "Identical delivery everywhere" ], 0,
    "First-of-a-kind EPR projects have experienced major schedule and budget difficulties.", :naog, -1, 3,
    "Delivery risk is foundational because delayed replacement costs money and may miss capacity needs." ],
  [ "How is Hinkley Point C's electricity supported?",
    [ "Only by charitable donations", "A long-term contract that guarantees an inflation-linked strike price", "Free fuel from government", "A ban on competing generation" ], 1,
    "Its Contract for Difference tops market revenue up to a contractual strike price, or recovers excess when market prices are higher.", :naog, -1, 3,
    "Consumer financing commitments are central to judging affordability." ],
  [ "Why do construction delays particularly raise nuclear costs?",
    [ "Uranium disappears during construction", "Reactors pay carbon tax before operating", "Large upfront capital accrues financing costs before revenue begins", "Workers cannot be paid monthly" ], 2,
    "Capital-intensive projects borrow and commit equity for years; delay increases interest and postpones generation.", :naog, -1, 3,
    "Financing is a principal determinant of nuclear electricity cost." ],
  [ "What is decommissioning?",
    [ "Routine refuelling", "Selling electricity", "Building transmission cables", "Defuelling, dismantling and cleaning a closed nuclear site" ], 3,
    "Decommissioning manages radioactive plant and materials after generation ends and can take decades.", :nda, -1, 2,
    "Lifecycle cost extends well beyond the operating period." ],
  [ "Who ultimately bears substantial costs and liabilities for the UK's historic civil nuclear legacy?",
    [ "The public sector", "Only current station visitors", "Foreign electricity consumers", "Nobody" ], 0,
    "The NDA is publicly funded to clean up historic sites, with very large long-term provisions.", :nda, -1, 3,
    "Legacy liabilities are a major fiscal consideration and warning for funding design." ],
  [ "What is a small modular reactor (SMR)?",
    [ "A household reactor", "A lower-output reactor intended for factory-based modular manufacture", "A battery", "A gas turbine renamed nuclear" ], 1,
    "SMRs aim to repeat standard modules and reduce project size, but commercial cost and delivery performance remain to be demonstrated at scale in the UK.", :gov, 1, 2,
    "SMRs could alter future delivery economics but remain less proven than existing reactor fleets." ],
  [ "Is uranium a renewable energy source?",
    [ "Yes, replenished daily", "Yes, because reactors make sunlight", "No; it is a finite mined fuel", "No fuel is used" ], 2,
    "Uranium resources are finite, although fuel is energy-dense and recycling or advanced reactors can extend utilisation.", :iaea, -1, 2,
    "Fuel sustainability and supply security are significant long-run considerations." ],
  [ "Compared with fossil-fuel plants, how much fuel volume does nuclear require for a given energy output?",
    [ "Far more", "Exactly equal", "No measurable fuel", "Far less because nuclear fuel is highly energy-dense" ], 3,
    "Small quantities of uranium contain very large amounts of usable energy.", :iaea, 1, 2,
    "Fuel density bears on stockpiling, transport and energy-security arguments." ],
  [ "Can nuclear fuel be stockpiled more readily than continuous pipeline gas supplies?",
    [ "Yes, stations can hold long fuel inventories", "No, uranium evaporates daily", "Only for one hour", "No fuel crosses borders" ], 0,
    "Low fuel volumes permit inventories covering long operating periods, though enrichment and fabrication supply chains remain international.", :iea, 1, 3,
    "Resilience to short-term fuel disruption is central to the energy-security case." ],
  [ "Does building nuclear remove the need for electricity networks, storage or flexible resources?",
    [ "Yes", "No; a reliable system still needs networks and balancing", "Only in Scotland", "Only if demand is constant forever" ], 1,
    "Large units can also create substantial contingency requirements when one trips offline.", :iea, -1, 3,
    "Whole-system requirements are foundational to comparing nuclear with alternative portfolios." ],
  [ "What happens to system reserve needs when one very large generating unit suddenly disconnects?",
    [ "They vanish", "Demand becomes zero", "Enough reserve must respond to cover the lost unit", "All wind farms close" ], 2,
    "Grid operators plan for the largest credible loss, so unit size affects reserve procurement.", :iea, -1, 2,
    "Large-unit contingency is a significant system cost." ],
  [ "Do wind and nuclear necessarily exclude one another in a low-carbon system?",
    [ "Yes, by physical law", "Yes, because both use turbines", "Only one can connect nationally", "No; they can contribute different output characteristics" ], 3,
    "System portfolios can combine variable renewables, firm generation, storage, interconnection and demand response.", :ipcc, 0, 3,
    "The proposition concerns replacement, but realistic alternatives are portfolios rather than one technology." ],
  [ "What proportion of UK respondents supported nuclear power generally in the Winter 2025 attitudes survey?",
    [ "44%", "4%", "94%", "0%" ], 0,
    "Support was 44%, opposition 11%, with a large neutral or don't-know group.", :desnz, 0, 1,
    "Public opinion is contextual rather than evidence of technical merit." ],
  [ "How did support for a nuclear station in respondents' local area compare with opposition in Spring 2026?",
    [ "Support was unanimous", "Support was 24% and opposition 35%", "Opposition was zero", "Support was 80% and opposition 2%" ], 1,
    "Local support was lower than general support, illustrating a siting challenge.", :desnz, -1, 2,
    "Local consent affects whether replacement projects can be delivered." ],
  [ "What concerns did local opponents report most frequently?",
    [ "Too little carbon dioxide", "Excessively small sites", "Safety/security and radioactive-waste disposal", "Lack of fossil fuel combustion" ], 2,
    "Safety and security led, followed by waste disposal and environmental concerns.", :desnz, -1, 2,
    "These concerns identify major social constraints, though polling does not determine actual risk." ],
  [ "Would closing nuclear stations without replacement necessarily reduce electricity demand?",
    [ "Yes, automatically", "Yes, by the same megawatts", "Only household demand", "No; their output must be replaced or demand separately reduced" ], 3,
    "Retirement removes supply capacity, not consumers' need for electricity.", :digest, 1, 3,
    "The counterfactual replacement source is foundational to assessing emissions, cost and security." ],
  [ "What comparison is required to judge whether new nuclear is cost-effective?",
    [ "Its whole-system cost and risk against feasible low-carbon alternatives", "Only its fuel price", "Only its cooling-tower height", "Its nameplate capacity alone" ], 0,
    "A fair comparison includes construction, finance, operation, networks, balancing, firm capacity, waste and decommissioning.", :naa, 0, 3,
    "Cost-effectiveness depends on the full alternative system, not a single headline price." ],
  [ "What is the most defensible synthesis of evidence about building new UK nuclear stations to replace retiring nuclear capacity?",
    [ "Nuclear is costless and risk-free", "Nuclear supplies firm low-carbon power, but projects carry material cost, delivery, accident and waste obligations", "Nuclear has lifecycle emissions identical to coal", "Retiring capacity needs no replacement decision" ], 1,
    "Nuclear can contribute reliable low-carbon electricity and energy security; whether new plants are advisable turns on delivery, finance, safety, waste and alternatives.", :iea, 0, 3,
    "A balanced synthesis of the principal benefits and burdens is foundational to an informed opinion." ]
], NUCLEAR_POWER_SOURCES)
