require_relative "fact_bank"

VOTING_REFORM_SOURCES = {
  commons: [ "House of Commons Library: Voting systems in the UK", "https://commonslibrary.parliament.uk/research-briefings/sn04458/" ],
  post: [ "UK Parliament POST: Elections and their reform", "https://post.parliament.uk/elections-and-their-reform/" ],
  ec: [ "Electoral Commission: How MPs are elected", "https://www.electoralcommission.org.uk/voting-and-elections/how-elections-work/types-elections/uk-parliamentary-general-election" ],
  election_2024: [ "House of Commons Library: General election 2024 results", "https://commonslibrary.parliament.uk/research-briefings/cbp-10009/" ],
  ipu: [ "Inter-Parliamentary Union: Electoral systems", "https://www.ipu.org/resources/publications/reference/2016-07/electoral-system-design-ipu-primer" ],
  ace: [ "ACE Electoral Knowledge Network: Electoral systems", "https://aceproject.org/ace-en/topics/es/esd/default" ],
  nz: [ "New Zealand Electoral Commission: MMP", "https://elections.nz/democracy-in-nz/what-is-new-zealands-system-of-government/what-is-mmp/" ],
  parliament: [ "UK Parliament: Hung parliaments", "https://www.parliament.uk/about/how/elections-and-voting/general/hung-parliament/" ]
}.freeze

VOTING_REFORM_FACTS = FactBank.build([
  [ "How is an MP elected under first past the post?",
    [ "The candidate with the most votes in the constituency wins", "A candidate must win over 50%", "National party vote alone determines every seat", "The House of Lords appoints the winner" ], 0,
    "Each constituency elects one MP; a plurality is sufficient even without a majority.", :ec, 0, 3,
    "The incumbent system's basic mechanism is foundational to comparing it with reform." ],
  [ "What is the central aim of proportional representation?",
    [ "Guaranteeing one-party government", "Making parties' seat shares broadly reflect vote shares", "Removing political parties", "Giving every constituency two MPs" ], 1,
    "PR systems translate votes into seats more proportionally, though designs vary.", :commons, 1, 3,
    "Proportionality is the approved proposition's defining intended benefit." ],
  [ "Did Labour win a majority of UK votes in the 2024 general election?",
    [ "Yes, over 60%", "Yes, exactly 50%", "No; it won about 34% while securing a large Commons majority", "No; it won under 10%" ], 2,
    "Labour won roughly one-third of votes but nearly two-thirds of seats.", :election_2024, 1, 3,
    "The latest election's vote-seat disparity directly illustrates the reform question." ],
  [ "Under FPTP, what is a 'safe seat'?",
    [ "A seat exempt from elections", "A seat reserved for a minister", "A seat with no registered voters", "A constituency one party is highly likely to retain" ], 3,
    "Large established margins make some constituencies unlikely to change hands.", :post, 1, 2,
    "Safe seats affect competition and the practical influence of votes." ],
  [ "What is tactical voting?",
    [ "Supporting a less-preferred viable candidate to affect who wins", "Voting twice", "Drawing constituency boundaries", "MPs voting in Parliament" ], 0,
    "A voter may back a viable alternative rather than a favourite with little local winning chance.", :post, 1, 2,
    "The incentive to vote tactically is a significant behavioural effect of FPTP." ],
  [ "Does 'proportional representation' identify one single electoral formula?",
    [ "Yes, closed lists only", "No; list, STV and mixed systems are among several designs", "Yes, STV only", "No; it means hereditary appointment" ], 1,
    "PR is a family of systems with materially different ballots, districts and constituency links.", :commons, 0, 3,
    "Design diversity is foundational because the proposition leaves the precise PR system open." ],
  [ "Which system is used for elections to the Scottish Parliament?",
    [ "Pure FPTP", "Hereditary selection", "The Additional Member System", "A national presidential ballot" ], 2,
    "Scotland combines constituency members with regional list members to improve proportionality.", :commons, 1, 2,
    "Domestic experience shows mixed-member proportional voting is administratively feasible." ],
  [ "Which proportional system is used for Northern Ireland Assembly elections?",
    [ "Block vote", "Closed national list", "FPTP", "Single Transferable Vote" ], 3,
    "Voters rank candidates in multi-member constituencies under STV.", :commons, 1, 2,
    "Existing UK use supplies relevant experience with preferential PR." ],
  [ "What usually happens to disproportionality when district magnitude—the number elected per district—increases under PR?",
    [ "It generally decreases", "It necessarily increases", "It becomes unrelated to votes", "All local representation ends" ], 0,
    "Larger multi-member districts generally allow seat shares to track votes more closely.", :ace, 1, 2,
    "District size exposes a central trade-off between proportionality and locality." ],
  [ "What electoral threshold does in a list-PR system?",
    [ "Sets a minimum turnout", "Sets a minimum vote share for representation", "Caps a party's seats", "Requires every MP to win 50%" ], 1,
    "Thresholds limit representation for very small parties and affect proportionality and fragmentation.", :ace, -1, 3,
    "Threshold choice strongly influences which parties enter Parliament." ],
  [ "Compared with FPTP, what does PR usually do for smaller parties with geographically dispersed support?",
    [ "Bans them", "Leaves outcomes necessarily identical", "Makes winning representation more likely", "Requires them to contest one seat only" ], 2,
    "Votes need not be concentrated in a few constituencies to translate into seats.", :ipu, 1, 3,
    "Representation of dispersed voters is a central consequence of PR." ],
  [ "Can a geographically concentrated party perform well under FPTP despite a modest UK-wide vote share?",
    [ "Never", "Only with House of Lords approval", "Only under compulsory voting", "Yes, by winning pluralities in concentrated constituencies" ], 3,
    "FPTP rewards geographic concentration, so regional parties can convert votes efficiently.", :election_2024, 0, 2,
    "This qualifies simplistic comparisons based only on national vote share." ],
  [ "What is an 'overhang seat' in mixed-member proportional systems?",
    [ "A constituency seat won beyond a party's proportional entitlement", "An unelected minister", "A vacant seat", "A seat shared by two MPs" ], 0,
    "Some MMP designs add balancing seats or enlarge Parliament when constituency wins exceed entitlement.", :nz, -1, 1,
    "This is a narrower implementation issue rather than the principal reform choice." ],
  [ "Under New Zealand's MMP system, how many votes does a voter ordinarily cast?",
    [ "One transferable vote", "Two: a party vote and an electorate vote", "One vote for prime minister", "As many as desired" ], 1,
    "The party vote principally determines proportional seat entitlement; the electorate vote chooses a local MP.", :nz, 1, 2,
    "MMP demonstrates one way to combine proportionality and geographic representation." ],
  [ "Does PR necessarily abolish constituency representatives?",
    [ "Yes in every design", "Yes unless turnout exceeds 50%", "No; STV and mixed systems retain geographic constituencies", "No, because constituencies become hereditary" ], 2,
    "Several PR families preserve local or regional representation.", :commons, 1, 3,
    "Whether voters retain identifiable local representatives is a central concern." ],
  [ "What is a common relationship between PR and coalition government?",
    [ "PR legally requires the same coalition forever", "PR makes coalitions impossible", "PR guarantees a majority to the largest party", "PR tends to make multi-party bargaining more common" ], 3,
    "More proportional party representation often makes single-party majorities less frequent, though not impossible.", :ipu, -1, 3,
    "Government formation and accountability are central trade-offs in electoral-system choice." ],
  [ "What is a hung parliament?",
    [ "No party has an overall Commons majority", "All MPs have resigned", "The Lords rejects an election", "The electorate is tied exactly" ], 0,
    "Parties may negotiate a coalition, confidence arrangement or minority government.", :parliament, 0, 2,
    "Understanding hung parliaments is significant to evaluating stability claims." ],
  [ "Can FPTP produce a hung parliament?",
    [ "Never", "Yes", "Only after PR", "Only if voting is compulsory" ], 1,
    "The UK experienced hung parliaments under FPTP, including after the 2010 and 2017 elections.", :parliament, 0, 2,
    "This prevents attributing coalition or minority government exclusively to PR." ],
  [ "What does the Gallagher index measure?",
    [ "Turnout", "District population", "Disproportionality between votes and seats", "Government duration" ], 2,
    "It summarises differences between parties' vote and seat shares.", :post, 0, 1,
    "The metric is useful context but not itself a normative reason to reform." ],
  [ "What may happen to the number of represented parties under PR?",
    [ "It must fall to two", "Parties become illegal", "It cannot change", "It often increases, depending on thresholds and district size" ], 3,
    "Lower barriers can support more parties, while thresholds constrain fragmentation.", :ipu, 0, 3,
    "Party-system fragmentation materially affects voter choice and government formation." ],
  [ "What does a closed party list allow voters to choose?",
    [ "A party, while the party-determined order allocates its elected candidates", "Any individual candidates across all parties", "Only a constituency independent", "The prime minister directly" ], 0,
    "Closed lists give parties control over candidate ordering.", :ace, -1, 2,
    "Candidate control is significant when assessing voter choice within PR." ],
  [ "What does an open-list system add to a party vote?",
    [ "Compulsory voting", "Some voter influence over which party candidates take seats", "Single-member plurality", "Appointment by judges" ], 1,
    "Open lists permit preference votes among a party's candidates.", :ace, 1, 2,
    "This shows that party-list PR need not remove candidate choice." ],
  [ "Under STV, how does a voter express preferences?",
    [ "By choosing one party only", "By approving the government", "By ranking candidates", "By drawing district boundaries" ], 2,
    "Votes transfer according to rankings when candidates are elected or eliminated.", :commons, 1, 2,
    "The ballot and transfer mechanism shape voter choice and representation." ],
  [ "What can boundary changes affect under FPTP?",
    [ "Only the colour of ballot papers", "The legal voting age", "The size of Parliament only", "How efficiently parties' votes translate into seats" ], 3,
    "Because seats are winner-take-all, the placement of boundaries can influence outcomes, even with independent boundary reviews.", :post, -1, 2,
    "Boundary sensitivity is a significant feature of the present system." ],
  [ "What is a possible accountability advantage of single-member FPTP constituencies?",
    [ "One clearly identifiable local MP", "Perfect national proportionality", "No party discipline", "Every voter backs the winner" ], 0,
    "A constituent has one designated MP, although other systems can also provide local representatives.", :ipu, -1, 2,
    "Local accountability is a significant argument for retaining FPTP." ],
  [ "What is a possible accountability criticism of coalition government?",
    [ "Coalitions cannot pass laws", "Voters may find responsibility for compromises less clear", "Coalitions prohibit manifestos", "Coalitions require unelected MPs" ], 1,
    "Post-election bargaining can blur which party is responsible, though coalition agreements can make compromises explicit.", :ipu, -1, 2,
    "Clarity of responsibility matters when weighing proportional outcomes against governance." ],
  [ "Would PR ensure that every individual voter's preferred candidate wins?",
    [ "Yes", "Yes if turnout is high", "No; it improves aggregate proportionality but cannot satisfy every preference", "No, because nobody is elected" ], 2,
    "No electoral system makes every ballot victorious; PR principally reduces aggregate vote-seat distortion.", :ace, 0, 2,
    "This guards against overstating the reform's benefits." ],
  [ "Can electoral-system change alter how parties campaign and where they seek votes?",
    [ "No", "Only ballot colour changes", "Only incumbent MPs notice", "Yes; incentives follow the votes and places that can affect seats" ], 3,
    "FPTP focuses effort on marginal seats; proportional systems can make votes across broader areas electorally consequential.", :post, 1, 3,
    "Campaign incentives affect political attention received by different voters." ],
  [ "What question must be settled before implementing the approved proposition?",
    [ "Which proportional design, districts and thresholds to use", "Whether elections should count votes", "Whether Parliament has MPs", "Whether parties may publish names" ], 0,
    "PR's consequences depend materially on system design; the proposition establishes direction, not a complete statute.", :commons, 0, 3,
    "Unspecified design choices are foundational to judging feasibility and likely outcomes." ],
  [ "What is the fairest overall conclusion from comparative evidence?",
    [ "FPTP dominates PR on every criterion", "PR improves vote-seat proportionality but trades against features such as simplicity, local linkage or single-party government depending on design", "Every PR system is identical", "Electoral systems have no behavioural effects" ], 1,
    "Electoral systems optimise different values; no design maximises proportionality, simplicity, local representation and decisive government simultaneously.", :ipu, 0, 3,
    "A balanced synthesis of the principal benefit and trade-offs is foundational to an informed opinion." ]
], VOTING_REFORM_SOURCES)
